function PlotLatencyPerCondition(T, outputFolder)
% PlotLatencyPerCondition
%
% Generates boxplot + swarmplot figures for response latency measurements
% from transplanted and sham retinal MEA recordings.
%
% This function takes the latency table T generated by
% collectDeltaFR_transplant_sham and plots peak latency across degeneration
% stage and treatment group.
%
% The function generates four sets of plots:
%
%   PART 1:
%       ON and OFF cells plotted separately for each light condition.
%
%   PART 2:
%       ON and OFF cells plotted separately with all three light conditions
%       combined.
%
%   PART 3:
%       All responsive cell types combined for each light condition.
%
%       Included cell types:
%           ON
%           OFF
%           ONOFF
%           unconventional
%
%   PART 4:
%       All responsive cell types combined across all three light conditions.
%
% INPUTS:
%   T : MATLAB table containing latency metrics.
%
%       Required variables:
%           Stage
%           Group
%           CellType
%           LightCondition
%           peakLatency
%
%       Usually generated by:
%           collectDeltaFR_transplant_sham
%
%   outputFolder : folder where output figures will be saved.
%
% OUTPUTS:
%   This function does not return variables directly.
%
%   It saves PNG figures to outputFolder.
%
% GROUPING:
%   The four plotted groups are:
%       early degeneration_SHAM
%       early degeneration_NRL
%       late degeneration_SHAM
%       late degeneration_NRL
%
% STATISTICS:
%   Pairwise comparisons are performed using Wilcoxon rank-sum tests
%   using ranksum().
%
%   Tested comparisons:
%       early SHAM vs early NRL
%       late SHAM  vs late NRL
%       early SHAM vs late NRL
%
% SIGNIFICANCE LABELS:
%       ns    p >= 0.05
%       *     p < 0.05
%       **    p < 0.01
%       ***   p < 0.001
%
% NOTE:
%   The plotted value is peakLatency, not onsetLatency.
%
%   In the three-conditions-combined plots, n represents the number of
%   cell-condition observations, not necessarily the number of unique cells.

%% Copy input table
% Work on a copy to avoid modifying the original latency table.

T_plot = T;

%% Exclude unresponsive cells
% Latency plots only include responsive cell classes.

T_plot = T_plot(string(T_plot.CellType) ~= "unresponsive", :);

%% Define original stage and group order
% These variables are kept for readability. The actual plotting order is
% defined below by plotGroupOrder.

stageOrder = ["early degeneration", "late degeneration"];
groupOrder = ["SHAM", "NRL"];

%% Define cell-type groups
% Original individual cell types plotted separately.
cellTypes = ["ON", "OFF"];

% Combined responsive category.
% Unresponsive cells are excluded.
allCombinedTypes = ["ON", "OFF", "ONOFF", "unconventional"];

%% Define plotting order
% Group labels are constructed as:
%   Stage + "_" + Group

plotGroupOrder = [
    "early degeneration_SHAM"
    "early degeneration_NRL"
    "late degeneration_SHAM"
    "late degeneration_NRL"
];

%% Extract light-condition labels
% LightCondition may be categorical, numeric, or string depending on how the
% input table was generated.

if iscategorical(T_plot.LightCondition)
    conditions = categories(T_plot.LightCondition);
else
    conditions = unique(T_plot.LightCondition);
end

% ======================================================
% PART 1: ON and OFF cells separately, per light condition
% ======================================================
for c = 1:numel(conditions)

    cond = conditions(c);

    for ct = 1:numel(cellTypes)

        cellType = cellTypes(ct);

        %% Select one light condition
        if iscategorical(T_plot.LightCondition)
            idxCond = T_plot.LightCondition == categorical(cond);
            condLabel = string(cond);
        else
            idxCond = T_plot.LightCondition == cond;
            condLabel = string(cond);
        end

        %% Select one cell type
        idxCell = string(T_plot.CellType) == cellType;

        S = T_plot(idxCond & idxCell, :);

        %% Add plotting group and missing-group placeholders
        S = addPlotGroup(S, plotGroupOrder, cellType, cond);

        if height(S) == 0
            continue;
        end

        %% Generate and save figure
        fig = makePlot(S, plotGroupOrder, ...
            sprintf('%s cells, light condition %s', cellType, condLabel));

        saveas(fig, fullfile(outputFolder, ...
            sprintf('%s_cells_latency_condition_%s.png', ...
            cellType, condLabel)));

        close(fig);
    end
end

% ======================================================
% PART 2: ON and OFF cells separately, three conditions combined
% ======================================================
for ct = 1:numel(cellTypes)

    cellType = cellTypes(ct);

    %% Select one cell type without filtering by light condition
    idxCell = string(T_plot.CellType) == cellType;

    S1 = T_plot(idxCell, :);

    S1 = addPlotGroup(S1, plotGroupOrder, cellType, "");

    if height(S1) == 0
        continue;
    end

    %% Generate and save figure
    fig = makePlot(S1, plotGroupOrder, ...
        sprintf('%s cells, three light conditions combined', cellType));

    saveas(fig, fullfile(outputFolder, ...
        sprintf('%s_cells_latency_three_conditions_combined.png', ...
        cellType)));

    close(fig);
end

% ======================================================
% PART 3: All responsive cell types combined, per light condition
% ======================================================
for c = 1:numel(conditions)

    cond = conditions(c);

    %% Select one light condition
    if iscategorical(T_plot.LightCondition)
        idxCond = T_plot.LightCondition == categorical(cond);
        condLabel = string(cond);
    else
        idxCond = T_plot.LightCondition == cond;
        condLabel = string(cond);
    end

    %% Select all responsive cell types
    idxCell = ismember(string(T_plot.CellType), allCombinedTypes);

    S_all = T_plot(idxCond & idxCell, :);

    S_all = addPlotGroup(S_all, plotGroupOrder, "ALL", cond);

    if height(S_all) == 0
        continue;
    end

    %% Generate and save figure
    fig = makePlot(S_all, plotGroupOrder, ...
        sprintf('All responsive cells, light condition %s', condLabel));

    saveas(fig, fullfile(outputFolder, ...
        sprintf('ALL_cells_latency_condition_%s.png', condLabel)));

    close(fig);
end

% ======================================================
% PART 4: All responsive cell types combined, three conditions combined
% ======================================================
idxCell = ismember(string(T_plot.CellType), allCombinedTypes);

S_all_combined = T_plot(idxCell, :);

S_all_combined = addPlotGroup(S_all_combined, plotGroupOrder, "ALL", "");

if height(S_all_combined) > 0

    fig = makePlot(S_all_combined, plotGroupOrder, ...
        'All responsive cells, three light conditions combined');

    saveas(fig, fullfile(outputFolder, ...
        'ALL_cells_latency_three_conditions_combined.png'));

    close(fig);
end

fprintf('\nDone! All figures saved to: %s\n', outputFolder);

end

function S = addPlotGroup(S, plotGroupOrder, cellType, cond)
% addPlotGroup
%
% Adds plotting-group information to a subset of the latency table.
%
% The function creates:
%   S.PlotGroup : categorical group label based on Stage and Group
%   S.Xpos      : numeric x-position used for plotting
%
% It also adds NaN placeholder rows for missing groups so that all figures
% keep the same x-axis order.
%
% INPUTS:
%   S              : subset of the latency table
%   plotGroupOrder : desired order of plotted groups
%   cellType       : cell-type label used only for warning messages
%   cond           : light-condition label used only for warning messages
%
% OUTPUT:
%   S : updated table with PlotGroup and Xpos variables

    %% Return early if no data are available for this subset
    if height(S) == 0
        warning('No data for cellType=%s, cond=%s', cellType, cond);
        return;
    end

    %% Construct group label from Stage and Group
    S.PlotGroup = strcat(string(S.Stage), "_", string(S.Group));

    %% Convert PlotGroup to ordered categorical
    S.PlotGroup = categorical(S.PlotGroup, plotGroupOrder, 'Ordinal', true);

    %% Convert group category to numeric x-position
    S.Xpos = double(S.PlotGroup);

    %% Add NaN placeholder rows for missing groups
    % This ensures that all plots have the same x-axis layout even if a
    % particular stage/group has no observations.

    for pg = 1:numel(plotGroupOrder)

        thisGroup = plotGroupOrder(pg);

        if ~any(string(S.PlotGroup) == thisGroup)

            newRow = S(1, :);

            % Set plotting value to NaN so the placeholder is ignored by
            % boxchart, swarmchart, and statistical testing.
            newRow.peakLatency = NaN;

            % Optional: clear other latency-related metrics if they exist.
            if ismember('onsetLatency', S.Properties.VariableNames)
                newRow.onsetLatency = NaN;
            end

            if ismember('peakFR', S.Properties.VariableNames)
                newRow.peakFR = NaN;
            end

            if ismember('threshold', S.Properties.VariableNames)
                newRow.threshold = NaN;
            end

            if ismember('UnitID', S.Properties.VariableNames)
                newRow.UnitID = NaN;
            end

            %% Assign Stage and Group according to this placeholder group
            if startsWith(thisGroup, "early")
                newRow.Stage = categorical("early degeneration");
            else
                newRow.Stage = categorical("late degeneration");
            end

            if endsWith(thisGroup, "SHAM")
                newRow.Group = categorical("SHAM");
            else
                newRow.Group = categorical("NRL");
            end

            newRow.PlotGroup = categorical(thisGroup, ...
                plotGroupOrder, 'Ordinal', true);

            newRow.Xpos = pg;

            S = [S; newRow];
        end
    end
end

function fig = makePlot(S, plotGroupOrder, titleStr)
% makePlot
%
% Creates a boxchart + swarmchart figure for peak latency values across the
% predefined stage/group categories.
%
% INPUTS:
%   S              : table containing peakLatency and PlotGroup variables
%   plotGroupOrder : order of plotted groups
%   titleStr       : title shown on the figure
%
% OUTPUT:
%   fig : figure handle
%
% The function also:
%   - adds n labels above each group
%   - performs selected rank-sum tests
%   - annotates significance labels on the plot
%   - prints p values to the command window

    fig = figure;
    hold on;

    %% Plot distribution
    % boxchart shows the group distribution.
    % swarmchart overlays individual observations.

    boxchart(S.Xpos, S.peakLatency);
    swarmchart(S.Xpos, S.peakLatency, 35, 'filled');

    %% Format axes
    ylabel('Latency (s)');
    title(titleStr);

    xticks(1:numel(plotGroupOrder));
    xticklabels({'early SHAM', 'early NRL', 'late SHAM', 'late NRL'});
    xtickangle(45);

    %% Determine y-axis range for annotations
    yVals = S.peakLatency(~isnan(S.peakLatency));

    if isempty(yVals)
        yTop = 1;
        yBottom = 0;
    else
        yTop = max(yVals);
        yBottom = min(yVals);
    end

    yRange = yTop - yBottom;

    if yRange == 0
        yRange = 1;
    end

    %% Add n labels above each group
    for pg = 1:numel(plotGroupOrder)

        thisGroup = plotGroupOrder(pg);

        nThis = sum(string(S.PlotGroup) == thisGroup & ...
                    ~isnan(S.peakLatency));

        text(pg, yTop + 0.08 * yRange, sprintf('n=%d', nThis), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'bottom', ...
            'FontSize', 10);
    end

    %% Define statistical comparisons
    comparisons = [
        "early degeneration_SHAM", "early degeneration_NRL"
        "late degeneration_SHAM",  "late degeneration_NRL"
    ];

    yStar = yTop + 0.15 * yRange;

    %% Perform rank-sum tests and add significance annotations
    for comp = 1:size(comparisons, 1)

        g1 = comparisons(comp, 1);
        g2 = comparisons(comp, 2);

        x1 = find(plotGroupOrder == g1);
        x2 = find(plotGroupOrder == g2);

        data1 = S.peakLatency(string(S.PlotGroup) == g1);
        data2 = S.peakLatency(string(S.PlotGroup) == g2);

        data1 = data1(~isnan(data1));
        data2 = data2(~isnan(data2));

        %% Only test groups with at least two observations each
        if numel(data1) >= 2 && numel(data2) >= 2

            p = ranksum(data1, data2);
            starText = pToStars(p);

            %% Draw comparison bracket
            plot([x1 x1 x2 x2], ...
                [yStar yStar + 0.04 * yRange ...
                 yStar + 0.04 * yRange yStar], ...
                'k-', 'LineWidth', 1);

            %% Add significance label
            text(mean([x1 x2]), yStar + 0.06 * yRange, starText, ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'bottom', ...
                'FontSize', 12);

            fprintf('%s | %s vs %s: p = %.4g\n', ...
                titleStr, g1, g2, p);

            yStar = yStar + 0.18 * yRange;

        else

            fprintf('%s | %s vs %s: not tested (n1=%d, n2=%d)\n', ...
                titleStr, g1, g2, numel(data1), numel(data2));
        end
    end

    %% Expand y-axis so n labels and significance brackets are visible
    ylim([max(0, yBottom - 0.05 * yRange), yStar + 0.15 * yRange]);

    hold off;
end

function stars = pToStars(p)
% pToStars
%
% Converts a p value into a significance label.

    if p < 0.001
        stars = "***";
    elseif p < 0.01
        stars = "**";
    elseif p < 0.05
        stars = "*";
    else
        stars = "ns";
    end
end